service: user-endpoint

frameworkVersion: '3'
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  timeout: 500
  environment:
    DB_USER: ${env:DB_USER}
    DB_NAME: ${env:DB_NAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    PORT: ${env:PORT}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  get-user:
    handler: src/functions/get-user.handler
    events:
      - http:
          method: get
          path: user

custom:
  serverless-offline:
    httpPort: 4000