service: post-endpoint

frameworkVersion: '3'
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  timeout: 500
  environment:
    DB_USER: ${env:DB_USER}
    DB_NAME: ${env:DB_NAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    PORT: ${env:PORT}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  list-post:
    handler: src/functions/list-post.handler
    events:
      - http:
          method: get
          path: post/list
  get-post:
    handler: src/functions/get-post.handler
    events:
      - http:
          method: get
          path: post/{postId}

custom:
  serverless-offline:
    httpPort: 4001
    lambdaPort: 3003