service: like-endpoint

frameworkVersion: '3'
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  timeout: 500
  environment:
    DB_USER: ${env:DB_USER}
    DB_NAME: ${env:DB_NAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    PORT: ${env:PORT}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  add-like:
    handler: src/functions/add-like.handler
    events:
      - http:
          method: post
          path: like
  delete-like:
    handler: src/functions/delete-like.handler
    events:
      - http:
          method: delete
          path: like/{postId}

custom:
  serverless-offline:
    httpPort: 4002
    lambdaPort: 3004